INSERT INTO events (
  slug,
  title,
  summary,
  start_at,
  end_at,
  timezone,
  location,
  program_modes,
  duration_label,
  access_window_label,
  custom_fields,
  allowed_domains,
  invite_code_enabled,
  invite_code_hash,
  invite_code_hint,
  instant_approval,
  requires_payment,
  moodle_course_ids,
  moodle_cohort_ids,
  thank_you_message,
  status
) VALUES (
  'secure-ai-governance',
  'Secure AI Governance for Education Leaders',
  'A professional development program on secure AI adoption, governance evidence, risk decisions, and learning-sector implementation models.',
  '2026-06-10 09:00:00',
  '2026-06-10 15:00:00',
  'UTC',
  'Online / Hybrid',
  JSON_ARRAY('synchronous', 'instructor_led', 'hybrid'),
  'One-day facilitated program',
  'Live session with post-program resources',
  JSON_ARRAY(
    JSON_OBJECT('name', 'organization', 'label', 'Organization', 'type', 'text', 'required', true, 'moodle_shortname', 'organization'),
    JSON_OBJECT('name', 'job_title', 'label', 'Job title', 'type', 'text', 'required', true, 'moodle_shortname', 'jobtitle'),
    JSON_OBJECT('name', 'registration_type', 'label', 'Registration type', 'type', 'select', 'options', JSON_ARRAY('Faculty', 'School Leader', 'Government Partner', 'Other'), 'required', true, 'moodle_shortname', 'registrationtype')
  ),
  JSON_ARRAY('example.org', 'training.example.org'),
  0,
  NULL,
  NULL,
  1,
  0,
  JSON_ARRAY(101, 102),
  JSON_ARRAY(12),
  'Thank you for registering. Program details and platform access will be sent after verification and provisioning.',
  'published'
) ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  summary = VALUES(summary),
  program_modes = VALUES(program_modes),
  duration_label = VALUES(duration_label),
  access_window_label = VALUES(access_window_label),
  custom_fields = VALUES(custom_fields),
  allowed_domains = VALUES(allowed_domains),
  invite_code_enabled = VALUES(invite_code_enabled),
  invite_code_hash = VALUES(invite_code_hash),
  invite_code_hint = VALUES(invite_code_hint),
  moodle_course_ids = VALUES(moodle_course_ids),
  moodle_cohort_ids = VALUES(moodle_cohort_ids),
  status = VALUES(status);
